export const GET_USER_DETAILS = "GET_USER_DETAILS";
export const MOUNTED_BTC_DATA = "MOUNTED_BTC_DATA";
export const MOUNTED_ETH_DATA = "MOUNTED_ETH_DATA";
export const MOUNTED_BNB_DATA = "MOUNTED_BNB_DATA";
export const SELECTED_TRADE = "SELECTED_TRADE";
export const HISTRIC_DATA_FOR_TRADE = "HISTRIC_DATA_FOR_TRADE";
export const SELECTED_INTERVAL_TD = "SELECTED_INTERVAL_TD";
export const SELECTED_CURRENCY_TD = "SELECTED_CURRENCY_TD";