import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import SignUp from '../components/AuthFolder/SignUp'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Sign up Trade Botting</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/td.png" />

      </Head>
      {/* <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} /> */}
    
    <SignUp />
    </div>
  )
}
